app/src/main/graphql/com/imashnake/animite/ExampleQuery.graphql, app/src/main/graphql/com/imashnake/animite/schema.graphqls, app/src/main/java/com/imashnake/animite/MainActivity.kt, build.gradle
This logs anime with `id = 1`: `Data(media=Media(id=1, title=Title(romaji=Cowboy Bebop, english=Cowboy Bebop, native=カウボーイビバップ)))`
=> GraphQL requests

app/build.gradle.kts, app/src/main/java/com/imashnake/animite/MainActivity.kt, versions.properties
Added a bottom navigation bar (UI component only).
=> Bottom navigation bar UI

.github/PULL_REQUEST_TEMPLATE/feature.md
Created a PR template for features.
=> Created PR template

app/src/main/java/com/imashnake/animite/ui/elements/Home.kt
LazyColumn and LazyRow are similar to a RecyclerView in Jetpack Compose.
I'm learning Jetpack Compose so feel free to merge or reject this.
=> Use LazyColumn to list animes in the Home tab

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/feature.md, CONTRIBUTING.md
Created a PR template to make it easier for contributors to describe changes.
1. Added contribution conventions in `CONTRIBUTING.md`.
2. Fixed PR template (it hopefully works now).
N/A
=> Added a PR template

gradle/wrapper/gradle-wrapper.properties, versions.properties
Updated AGP and Gradle; and refresh versions.
Updated AGP and Gradle.
1. Reviewed release notes for [AGP](https://developer.android.com/studio/releases#bumblebee) and [Gradle](https://gradle.org/releases/).
2. Updated AGP to 7.1.3 and Gradle to 7.4.2.
3. Refreshed versions.
Built the app.
=> Updated AGP and Gradle

versions.properties
Updated Apollo Kotlin to 3.2.2
Updated Apollo Kotlin to 3.2.2.
1. Reviewed [release notes](https://github.com/apollographql/apollo-kotlin/releases) and updated Apollo Kotlin to 3.2.2.
Ran successfully,
=> Update Apollo Kotlin

gradle/libs.versions.toml
Created version references and updated Kotlin dependencies.
[Updated](https://kotlinlang.org/docs/releases.html#ide-support) Kotlin dependencies (and plugin) and grouped dependency versions in `libs.versions.toml`.
1. Created version references for Kotlin dependencies using the `version.ref` API.
2. Updated `datetime` to [0.3.3](https://github.com/Kotlin/kotlinx-datetime/releases/tag/v0.3.3).
Ran the app.
=> Updated Kotlin

gradle/libs.versions.toml
Created a version reference and updated AGP.
Updated AGP to [7.2.0](https://developer.android.com/studio/releases/gradle-plugin#7-2-0).
1. Created a version reference and updated AGP to 7.2.0 (no relevant API changes).
Ran the app.
=> Updated AGP

app/build.gradle.kts
Targeting and compiling to SDK 32.
1. Changed `targetSdk` and `compileSdk` to 32.
Ran the app.
=> Targeted API 32

gradle/libs.versions.toml
Updated Dagger to [2.42](https://github.com/google/dagger/releases/tag/dagger-2.42).
1. Created version references for Dagger and Hilt using `version.ref`.
2. Updated Dagger to 2.42.
Ran the app.
=> Updated Dagger

gradle/libs.versions.toml
Created version references for the other dependencies and added links to release notes.
1. Created `version.ref`s.
Ran the app.
=> Created version references

app/src/main/AndroidManifest.xml
Fixes #25. Removed support for landscape mode since the layout is messed up. 
1. Locked screen orientation in the manifest file.
Ran the app and confirmed that the app did not change orientation on rotating the device.
=> Remove landscape support

gradle/libs.versions.toml
Updated Apollo Kotlin to 3.3.0. 
1. Reviewed [release notes](https://github.com/apollographql/apollo-kotlin/releases/tag/v3.3.0) and updated Apollo Kotlin to 3.3.0.
Ran the app.
=> Updated Apollo Kotlin

gradle/libs.versions.toml
Updated Accompanist to `0.24.11-rc`.
1. Reviewed [release notes](https://github.com/google/accompanist/releases) and updated Accompanist.
Ran the app; there seem to be no changes related to system bar colors which is seemingly the only reason we use Accompanist. 
=> Updated Accompanist

app/build.gradle.kts, gradle/libs.versions.toml
Updating Compose and Kotlin now that they are compatible.
1. Updated Kotlin to 1.7.0 and Compose compiler to 1.2.0.
2. Separated out versions for the other Compose libraries since [this](https://android-developers.googleblog.com/2022/06/independent-versioning-of-Jetpack-Compose-libraries.html) happened.
3. Updated AGP to [7.2.1](https://developer.android.com/studio/releases/gradle-plugin#7-2-0).
Something about over-scroll and scrolling in general is messed up?
=> Update Kotlin and Compose

.github/workflows/build.yaml, .github/workflows/octocatgirl.yml, README.md, app/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml
1. Added the dependency analysis plugin.
2. Added action for releases.
3. Welcome OctoCatGirl!
:i_am_weeb:
=> GitHub Actions

app/src/main/java/com/imashnake/animite/dev/internal/Constants.kt, app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt, app/src/main/java/com/imashnake/animite/features/ui/MediaSmall.kt
[Coil Image Builder Recipe](https://coil-kt.github.io/coil/compose/#asyncimage)
* Converted AsyncImage(model = image...) to use an ImageRequest.Builder allowing for Coil config
* Enables more builder usages like `.error(Res.drawable...)` and `.fallback(Res.drawable...)`
* Could also consider `SubcomposeAsyncImage` which allows for a composable-scoped to provide a `CircularProgressIndicator()`
No regression in loading images, crossfade only happens on first load, afterwards it gets loaded from Coil cache which is near instant
=> COIL Crossfade

app/build.gradle.kts, core/build.gradle.kts, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, material-color-utilities/build.gradle.kts, profile/build.gradle.kts, rslash/build.gradle.kts
There are some [new Compose APIs](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.4.0-alpha01) that can help with the Search Bar refactor.
1. Reviewed release notes and updated dependencies.
2. Compose BOM.
App builds.
=> Updated dependencies

app/build.gradle.kts, app/src/main/java/com/imashnake/animite/di/NetworkModule.kt, gradle/libs.versions.toml
Added both SQLite for persistence, and memory for speed
1. Added relevant libraries.
2. Enabled caching for our ApolloClient.
Launch the app, close and re-launch again loads much faster as results come from cache.
=> Add data caching via Apollo

api/anilist/build.gradle.kts, api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/FlowExt.kt, app/build.gradle.kts, app/src/main/java/com/imashnake/animite/features/MainActivity.kt, build.gradle.kts, core/build.gradle.kts, gradle.properties, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, material-color-utilities/build.gradle.kts, profile/build.gradle.kts, rslash/build.gradle.kts, settings.gradle.kts
1. Update everything (I'm not gonna list them all, that's a lot)
2. Hilt compiler now uses KSP, KAPT is no more
3. K2 enabled
4. Android settings plugin applied
5. Migrated to jvmToolchain
6. Target SDK34
The app builds (fast) and runs
=> Update all dependencies & enable K2

app/build.gradle.kts, app/src/main/java/com/imashnake/animite/features/MainActivity.kt, gradle/libs.versions.toml
Removed Accompanist since `SystemUiController` is deprecated.
1. Replaced `SystemUiController` with `enableEdgeToEdge()`.
2. Removed `accompanist-placeholder`.
No behaviour changes.
[comment]: # (If changes were tested, replace this comment with a brief description of how you did so. Else replace it with "N/A".)
=> Removed Accompanist

app/src/main/java/com/imashnake/animite/features/MainActivity.kt, app/src/main/java/com/imashnake/animite/features/home/Home.kt, app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt, app/src/main/java/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt, app/src/main/java/com/imashnake/animite/features/theme/Theme.kt, app/src/main/java/com/imashnake/animite/features/ui/MediaSmall.kt, app/src/main/res/values/dimens.xml, core/src/main/kotlin/com/imashnake/animite/core/ui/Paddings.kt, core/src/main/kotlin/com/imashnake/animite/core/ui/ProgressIndicator.kt, core/src/main/res/values/dimens.xml, core/src/main/res/values/strings.xml, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt, rslash/src/main/kotlin/com/imashnake/animite/rslash/RSlashScreen.kt
Followed a certain convention for non-transitive R classes and made it clear that Profile and RSlash are not yet implemented.
1. Moved padding dimensions to `:core`.
2. Added "Coming Soon" on top of progress indicator.
3. Fixed cap on progress indicator.
4. Migrate to `LocalPaddings` by @boswelja.
Doesn't crash
=> R class shenanigans and Coming Soon

.github/workflows/create-release.yaml, app/build.gradle.kts
Sign release builds to fix #75.
1. [Sign release builds](https://github.com/boswelja/NASdroid/pull/180/files).
No
=> Sign release builds

app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt, app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt, app/src/main/res/values/dimens.xml, core/src/main/kotlin/com/imashnake/animite/core/ui/NestedScrollableContent.kt, core/src/main/kotlin/com/imashnake/animite/core/ui/layouts/BannerLayout.kt, core/src/main/kotlin/com/imashnake/animite/core/ui/layouts/TranslucentStatusBarLayout.kt, core/src/main/res/values/dimens.xml
New reusable `BannerLayout`.
1. Create `BannerLayout`.
`HomeScreen` and `MediaPage` are unchanged.
=> `BannerLayout`

app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt, app/src/main/java/com/imashnake/animite/features/ui/MediaSmall.kt, core/src/main/kotlin/com/imashnake/animite/core/ui/layouts/BannerLayout.kt
Added some animations to the Home Screen.
1. Added a cross fade when the media lists change.
2. Added enter/exit animations for `HomeRow`s.
3. Changed `offset` to lambda version and animated icon color.
y
=> Home Screen Animations

app/src/main/java/com/imashnake/animite/features/searchbar/SearchFab.kt, app/src/main/java/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt, gradle/libs.versions.toml
Reviewed release notes and updated dependencies.
1. `autoCorrect` was renamed to `autoCorrectEnabled`.
2. [`animateItemPlacement()` was deprecated and replaced with `animateItem()`](https://twitter.com/ianhlake/status/1775710792379216026).
3. Temporarily removed `imeNestedScroll()` because of https://issuetracker.google.com/issues/323708850.
yeah
=> Updated deps

api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistUserRepository.kt, core/src/main/kotlin/com/imashnake/animite/core/data/Resource.kt, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileViewModel.kt, profile/src/main/kotlin/com/imashnake/animite/profile/dev/internal/Constants.kt
1. Copied refreshing code from [boswelja/NASdroid](https://github.com/boswelja/NASdroid/blob/main/features/apps/ui/src/main/kotlin/com/nasdroid/apps/ui/installed/overview/InstalledAppsOverviewViewModel.kt).
Only one emission happens: From the network if refreshed and from the cache otherwise.
=> `MutableStateFlow`

settings.gradle.kts
=> Target SDK35

api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistMediaRepository.kt, api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/media/MediaList.kt, app/src/main/java/com/imashnake/animite/features/MainActivity.kt, app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt, app/src/main/java/com/imashnake/animite/features/home/HomeViewModel.kt, app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
For #135, we need to know the source of each media to add a unique key when the media is present in multiple lists.
1. Wrapped `List<Media.Small>` in a new `MediaList`.
2. Emit `MediaList` instead.
It works
=> Emit `MediaList`

app/src/main/java/com/imashnake/animite/dev/SharedContentKey.kt, app/src/main/java/com/imashnake/animite/features/MainActivity.kt, app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt, app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt, core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
Share media card text and media page title.
1. Share the text components.
teehee
=> Shared Element Transition -> HomeScreen to MediaPage (Part 3)

gradle/libs.versions.toml, renovate.json
1. Update Kotlin 2.0.0 -> 2.0.21.
2. Update KSP 2.0.0-1.0.22 -> 2.0.21-1.0.28.
erm
=> Update Kotlin and KSP

app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt, core/src/main/kotlin/com/imashnake/animite/core/ui/shaders/Ethereal.kt
Used [AGSL to add a shader](https://www.youtube.com/watch?v=soMl3k0mBx4).
1. Replaced the gradient in the banner with a custom shader.
looks cool
=> Added Banner Shader

core/src/main/kotlin/com/imashnake/animite/core/ui/Paddings.kt, core/src/main/res/values/dimens.xml
Moved dimens for paddings into Kotlin. A step towards #234 
App builds and runs as expected
=> No dimens for paddings

api/anilist/src/main/graphql/UserQuery.graphql, api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistUserRepository.kt, api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/media/Media.kt, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileViewModel.kt, profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Anime.kt
Added Manga lists (similar to Anime lists) on the profile screen.
1. Populated Manga tab.
workds
=> User Manga Lists

api/anilist/build.gradle.kts, api/mal/build.gradle.kts, api/preferences/build.gradle.kts, app/build.gradle.kts, build.gradle.kts, core/build.gradle.kts, gradle/libs.versions.toml, media/build.gradle.kts, navigation/build.gradle.kts, profile/build.gradle.kts, social/build.gradle.kts
1. [comment]: # (Summary of changes that reflects changes made in each commit.)
[comment]: # (If changes were tested, replace this comment with a brief description of how you did so. Else replace it with "N/A".)
=> Add dependencies for multiplatform

app/src/main/kotlin/com/imashnake/animite/AnimiteApplication.kt, gradle/libs.versions.toml
To help debugging https://github.com/coil-kt/coil/issues/2832
1. [comment]: # (Summary of changes that reflects changes made in each commit.)
[comment]: # (If changes were tested, replace this comment with a brief description of how you did so. Else replace it with "N/A".)
=> Enable debug logs for Coil

app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt, app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt, app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt, core/src/main/kotlin/com/imashnake/animite/core/extensions/PaddingValuesExt.kt, core/src/main/kotlin/com/imashnake/animite/core/ui/layouts/BannerLayout.kt, media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt, profile/src/main/kotlin/com/imashnake/animite/profile/tabs/About.kt, profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Favourites.kt, profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Media.kt
Stole https://github.com/uragiristereo/Mikansei/blob/main/core/ui/src/main/java/com/uragiristereo/mikansei/core/ui/extension/PaddingValues.kt
1. Replaced `PaddingValues` with stolen extension.
everything looks the same.
=> Steal `PaddingValuesExt`

app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt, app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt, app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt, navigation/src/main/kotlin/com/imashnake/animite/navigation/NavigationBar.kt, navigation/src/main/kotlin/com/imashnake/animite/navigation/NavigationBarPaths.kt, navigation/src/main/kotlin/com/imashnake/animite/navigation/NavigationRail.kt, navigation/src/main/res/values/dimens.xml, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
Reopen #284.
1. Brought back navigation rail (again).
brah
=> Re: Navigation Rail in Landscape Mode

app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt
Deeplinks broke in #291; https://issuetracker.google.com/issues/395712033#comment8
1. Explicitly specify action in nav deep link builder.
Login works now
=> Fix Login -> Explicitly Specify Action

gradle/libs.versions.toml, profile/build.gradle.kts, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileViewModel.kt, profile/src/main/res/values/strings.xml
Added dropdown with a log out option.
1. Added [`saket-cascade`](https://saket.github.io/cascade/compose/).
2. Added dropdown with log out item.
logs out!
=> Logout Dropdown

api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistUserRepository.kt, core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt, navigation/src/main/kotlin/com/imashnake/animite/navigation/NavigationBarPaths.kt, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileViewModel.kt, profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Media.kt, profile/src/main/kotlin/com/imashnake/animite/profile/tabs/ProfileTab.kt, profile/src/main/res/values/strings.xml
Implemented refresh for the profile screen.
1. Added a refresh option to the drop down menu.
seems to work fine:
=> Profile Screen -> Refresh

api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistMediaRepository.kt, app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt, app/src/main/kotlin/com/imashnake/animite/features/home/HomeViewModel.kt, profile/src/main/kotlin/com/imashnake/animite/profile/ProfileViewModel.kt
1. Added pull to refresh to the home screen.
yes
=> Home Screen -> Refresh
