imashnake0/Animite

- app/build.gradle.kts
- versions.properties
Went through [release notes](https://github.com/apollographql/apollo-kotlin/releases/tag/v3.2.0) and updated Apollo Kotlin to 3.2.0.
1. Updated Apollo Kotlin to 3.2.0.
2. Resolved `TODO`: `refreshVersions` [error](https://github.com/jmfayard/refreshVersions/issues/507) was [fixed](https://github.com/apollographql/apollo-kotlin/pull/3898) in this release.
> Updated Apollo Kotlin

- app/src/main/java/com/imashnake/animite/ui/elements/home/Home.kt
- app/src/main/java/com/imashnake/animite/ui/elements/home/MediaSmall.kt
- app/src/main/java/com/imashnake/animite/ui/elements/home/MediaSmallRow.kt
1. Applied vertical padding (`12.dp`) in the Home path.
2. Implemented [`horizontalArrangement`](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/Arrangement) in `MediaSmallRow`'s `LazyRow`, this replaces the padding modifier in the `MediaSmall` card.
3. Changed the padding modifier in `MediaSmallRow`'s `LazyRow` to `contentPadding`, it is like [`clipToPadding`](https://stackoverflow.com/questions/66435811/jetpack-compose-cliptopadding) in xml.
The layout of the Home path is the same.
> Refactor Home path

- app/src/main/java/com/imashnake/animite/ui/elements/home/SearchBar.kt
Changed the behavior of the `SearchBar` a little bit.
1. Replace the `Column` to a `LazyColumn` for the search results.
2. Changed a little bit the `SearchBar` style, trying to make it more compacted.
The behavior of the `SearchBar` is the same as before, ~~only need to do the close button action to collapse the `ExpandedSearchBar`~~.
> Search Bar Improvements

- app/src/main/java/com/imashnake/animite/features/MainActivity.kt
MainActivity contained a bunch of Composable stuff, but typically it should only contain Activity-specific things.
1. Extracted `MainScreen` Composable from `MainActivity`
2. Refactored to use Scaffold for a number of benefits
Main screen still appears, and nothing is significantly different (that I can see)
> Extract `MainScreen` Composable and misc cleanups

- .github/workflows/notify-release-created.yaml
Trigger on release created, rather than published.
N/A.
> Fixed `notify-release-created.yaml`

- app/src/main/java/com/imashnake/animite/features/MainActivity.kt
- app/src/main/java/com/imashnake/animite/features/searchbar/SearchFab.kt
- app/src/main/java/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt
Attempting to further break down the search component, as well as clean up improper color API usages.
This is a step towards extracting "search" as a feature
1. Extracted a new SearchFab Composable
2. SearchFab now fully uses inherited colors, and avoids redefining them everywhere.
Seach bar has no visible UI/UX changes (that I have noticed)
> Further decouple search elements

- .github/workflows/build-debug.yaml
- .github/workflows/create-release.yaml
- .github/workflows/pull-request-checks.yaml
- api/anilist/build.gradle.kts
- app/build.gradle.kts
- build.gradle.kts
- core/build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- material-color-utilities/build.gradle.kts
- profile/build.gradle.kts
- rslash/build.gradle.kts
- settings.gradle.kts
1. Updated AGP to [8.0.0](https://developer.android.com/build/releases/gradle-plugin#8-0-0).
- [JDK 17 required to run AGP 8.0](https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp).
- Also updated workflow to reflect this.
- Renamed `packagingOptions` to `packaging`.
3. Updated Gradle to [8.1.1](https://docs.gradle.org/8.1.1/release-notes.html).
- Removed supressions for: [[#22797](https://github.com/gradle/gradle/issues/22797)] - Version catalog accessors for plugin aliases shown as errors in IDE kotlin script editor.
- [`targetSdk` is deprecated and will be removed from library DSL in v9.0](https://developer.android.com/reference/tools/gradle-api/7.4/com/android/build/api/dsl/LibraryBaseFlavor#targetSdk()).
- …
> Updated AGP and Gradle

- app/src/main/java/com/imashnake/animite/features/home/Home.kt
- app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
- app/src/main/java/com/imashnake/animite/features/searchbar/SearchFab.kt
- app/src/main/java/com/imashnake/animite/features/ui/MediaSmall.kt
- gradle/libs.versions.toml
- settings.gradle.kts
Reviewed release notes and updated dependencies.
1. `border` is now a `BorderStroke`.
2. Bumped `minSdk` to prevent "This app was built for an older version of Android...".
3. Auto-mirrored icons for RTL layouts.
Yes
[comment]: # (If changes were tested, replace this comment with a brief description of how you did so. Else replace it with "N/A".)
> Updated dependencies

- api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/media/Media.kt
The trailer section was shown with no thumbnail even thought it was null, deeplinking caused the app to crash.
1. Hid the trailer section when either of `site` or `id` is null.
Trailer section is hidden in "One Piece".
> Hide trailer when null

- api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/media/Media.kt
- app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
Replaced default thumbnails with `maxresdefault` and added two more fall backs.
1. Fallbacks: `maxresdefault` -> `sddefault` -> Default thumbnail from API.
- `maxresdefault` is on most entries.
- "Haikyuu!!" for `sddefault`.
- "Highschool of the Dead" for the default thumbnail. 
> Higher quality thumbnails

- app/build.gradle.kts
- build.gradle.kts
- core/build.gradle.kts
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- profile/build.gradle.kts
- rslash/build.gradle.kts
- settings.gradle.kts
Updated dependencies.
1. Updated AGP and Gradle:
- Updated AGP to 8.5.0: https://developer.android.com/build/releases/gradle-plugin
- Updated Gradle to 8.8: https://docs.gradle.org/8.8/release-notes.html; Accessors for Settings extensions in Kotlin DSL resolves https://github.com/gradle/gradle/issues/11210
2. Updated AndroidX libs.
3. Updated Coil.
4. Updated Compose artifacts.
What
> Updated deps

- api/anilist/src/main/graphql/UserQuery.graphql
- api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/profile/Viewer.kt
- app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
- core/src/main/kotlin/com/imashnake/animite/core/ui/Stats.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
- profile/src/main/res/values/strings.xml
Added the stats that appear in the "Overview" tab of Anilist.
1. Created a common `StatsRow` for `MediaPage` rankings and user's stats.
**Tested changes:** 👍 
> Added Stats to the User's About Tab

- app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt
- app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
Now the cards transition to the media page.
1. Shared bounds of the media cards and media page.
2. Used [shared element APIs](https://developer.android.com/develop/ui/compose/animation/shared-elements/) to handle a couple elements:
- [Changed `resizeMode`](https://developer.android.com/develop/ui/compose/animation/shared-elements/customize#resize-mode).
- [Clipped bounds to "a" corner radius](https://developer.android.com/develop/ui/compose/animation/shared-elements/customize#clip-overlays).
- [`skipToLookaheadSize` for text](https://developer.android.com/develop/ui/compose/animation/shared-elements/customize#skip-final).
- Changed shared bounds from image-to-image to image-to-card to prevent default translucent background of …
> Shared Element Transition -> `HomeScreen` to `MediaPage` (Part 2)

- app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt
- core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
Before this, we had `AnimatedContent` for `MediaSmallRow`'s `LazyRow` and `AnimatedVisibility` for `MediaSmallRow`. This PR removes both these animations and consolidates it into a single `AnimatedContent` animation for `HomeRow`.
1. Consolidated animations.
Looks pretty similar to the previous animation without the jank.
> Consolidated `HomeRow` Animations

- app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt
- app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
- app/src/main/res/values/dimens.xml
- core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
- core/src/main/res/values/dimens.xml
Initially, aspect ratio was used to configure the height of the media images, it should be something that we can change for creating a funi list. Now, we set a width to the cards and a height to the images since the height of the cards can change depending on `label`.
1. Stop using aspect ratio.
No UI changes.
> Stop Using Aspect Ratio

- app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt
- app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
- app/src/main/java/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt
- core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Anime.kt
Follow up to #207.
1. Extracted `imageHeight` and `cardWidth` so they are set for sure.
Profile media list is fixed now.
> Re: Stop Using Aspect Ratio

- .github/workflows/build-debug.yaml
- .github/workflows/create-release.yaml
- .github/workflows/pull-request-checks.yaml
- api/anilist/build.gradle.kts
- api/preferences/build.gradle.kts
- app/build.gradle.kts
- core/build.gradle.kts
- material-color-utilities/build.gradle.kts
- navigation/build.gradle.kts
- profile/build.gradle.kts
Android Studio is (or will very soon be) bundling Java 21, which means jvmToolchain(17) is an error. Merge this when you update your IDE
1. jvmToolchain 21
App still builds (I've been using these changes locally for a while
> jvmToolchain 21

- app/build.gradle.kts
- app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt
- app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
- media/build.gradle.kts
- media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
- profile/build.gradle.kts
- profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Anime.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/ProfileTab.kt
Now that #232 is merged, we can navigate to media pages from the profile screen.
1. Propagate required params and add callback.
Navigation works 👍 
> Navigate to `MediaPage` from `ProfileScreen`

- media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
Compose supports HTML parsing now (sort of). Merging this PR before making the details composable clickable to open a bottom sheet.
1. Replaced `AndroidView` with `Text` for the media description.
yep
> Replace `AndroidView` with `Text`

- media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
Open bottom sheet with media title and description.
1. Open modal bottom sheet.
hi
> Make Media Details Clickable

- api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistUserRepository.kt
- api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/profile/Viewer.kt
- app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
- core/src/main/kotlin/com/imashnake/animite/core/ui/ProgressIndicator.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/ProfileViewModel.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Media.kt
- profile/src/main/res/values/strings.xml
This adds a progress indicator for when the profile screen is loading and "No <Media>" fallback text to profile media tabs.
1. Linear progress indicator is shown on profile screen when it's loading.
2. Fallback text is shown on profile media tabs when there are no media collections.
HMMMMMMM
> Profile Screen Loading and Media Tab Fallback

- app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
- app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt
- core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
- media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
- media/src/main/res/values/dimens.xml
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Favourites.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Media.kt
Abstracts `MediaSmall` away from the rest of the app. This has a few advantages
- Callers don't need to manually specify width/height
- All areas are guaranteed to look the same, rather than expecting them to pass the same size in
- The funny size parameters are hidden from consumers
- Gets rid of a couple of dimen resources
1. Created MediaCard
2. Created CharacterCard
3. Migrated usages to new cards
4. Made MediaSmall internal
App runs and same info is displayed as before
> Hide MediaSmall behind MediaCard and CharacterCard

- app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt
- app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
- app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFab.kt
- app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt
- core/src/main/kotlin/com/imashnake/animite/core/extensions/ModifierExt.kt
- core/src/main/kotlin/com/imashnake/animite/core/extensions/PaddingValuesExt.kt
- core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
- core/src/main/kotlin/com/imashnake/animite/core/ui/layouts/BannerLayout.kt
- media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
- navigation/src/main/kotlin/com/imashnake/animite/navigation/NavigationBar.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/About.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Favourites.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Media.kt
Previously, we were relying on orientation values to handle some insets. This is NOT correct, and has even led to a few edge cases that weren't handled. I'm rewriting our inset handling to be orientation-agnostic.
1. Removed `landscapeCutoutPadding` (very bad)
2. Gutted any manual inset handling elsewhere
3. Rewrote MediaSmallRow to take a contentPadding
4. Rewrote screens to have one top-level WindowInsets (overridable), and apply it as needed
UI components do not overlap any system bars in any orientation or device configuration (this includes Foldables, and other unique form factors)
> Rewrite Inset Handling

- app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
Navigation rail padding was applied at a higher level.
1. Moved navigation rail padding to content padding of `HomeRow`.
yuh
> Home Screen -> Fix Start Padding in Landscape Mode

- app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt
- app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
- app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt
- media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
- media/src/main/kotlin/com/imashnake/animite/media/MediaPageViewModel.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Favourites.kt
- profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Media.kt
The media title already exists before navigation so we can pass and use it directly
1. Instead of fetching and setting the title, we can use the title from the previous screen.
Title is shown faster 👍 
> Media Page -> Pass Title in Nav Args
